version: "3.9"

services:
  midaz-console:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "midaz-console"
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

  midaz-server-mock:
    build:
      context: .
      dockerfile: Dockerfile-json-server
    container_name: "midaz-server-mock"
    restart: always
    depends_on:
      - midaz-console
    network_mode: "service:midaz-console"