services:
  midaz-console:
    container_name: console
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${MIDAZ_CONSOLE_PORT}:8081'
    env_file:
      - .env
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:8081/api/admin/health/ready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - console_network
      - transaction_network
      - auth_network
      - infra_network
      - ledger_network

networks:
  console_network:
    name: console_network
    driver: bridge
  transaction_network:
    name: transaction_network
    driver: bridge
  ledger_network:
    name: ledger_network
    driver: bridge
  auth_network:
    name: auth_network
    driver: bridge
  infra_network:
    name: infra_network
    driver: bridge
