version: '3.9'

services:
  midaz-console:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'midaz-console'
    restart: always
    ports:
      - '3000:3000'

  storybook:
    build:
      context: .
      dockerfile: Dockerfile-storybook
    container_name: 'storybook'
    restart: always

    ports:
      - '8080:8080'

networks:
  compose-bridge:
    driver: host
