'use client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { SideNavbar } from '@/components/SideNavBar'
import { Header } from '@/components/Header'
import { Suspense, useEffect, useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import { loadBindings } from 'next/dist/build/swc'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Midaz',
//   description: 'Generated by create next app'
// }

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const router = useRouter()
  const pathName = usePathname()
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (pathName === '/') {
      const defaultLocale = 'pt_BR'
      router.push(`/?lang=${defaultLocale}`)
      setLoading(true)
    }
  }, [pathName, router])

  return (
    <html lang="pt_BR">
      <body
        className={cn(
          'flex min-h-screen w-full bg-white text-black',
          inter.className
        )}
      >
        {loading && (
          <Suspense fallback={<p>Loading...</p>}>
            <SideNavbar />
            <div className="flex w-full flex-col">
              <Header />
              <div className="w-full p-8">{children}</div>
            </div>
          </Suspense>
        )}
      </body>
    </html>
  )
}
