import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { SideNavbar } from '@/components/SideNavBar'
import { Header } from '@/components/Header'
import Breadcrumb from '@/components/Breadcrumb'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Midaz',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'flex min-h-screen w-full bg-white text-black',
          inter.className,
          {
            'debug-screens': process.env.NODE_ENV === 'development'
          }
        )}
      >
        <SideNavbar />
        <div className="flex w-full flex-col">
          <Header />

          <div className="w-full p-8">
            <Breadcrumb
              homeElement={'..'}
              separator={<span> / </span>}
              activeClasses="font-bold"
              containerClasses="flex py-5"
              listClasses="hover:underline mx-1"
            />

            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
