name: Lighthouse CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lhci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Start app
        run: npm run start &
        env:
          PORT: 8081

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:8081 --timeout 60000

      - name: Run Lighthouse CI
        run: npm run lhci -- --ci

      # Verificar se o diretório .lighthouseci foi criado após a execução do LHCI
      - name: Check if .lighthouseci directory exists
        run: |
          echo "Checking for .lighthouseci directory..."
          if [ -d "midaz-console/.lighthouseci" ]; then
            echo ".lighthouseci directory exists."
            ls -alR midaz-console/.lighthouseci
          else
            echo ".lighthouseci directory does not exist."
          fi

      # Verificar a existência dos arquivos de relatório .html e .json após o LHCI
      - name: Check if reports exist in the directory
        run: |
          echo "Checking for report files in .lighthouseci..."
          ls -al midaz-console/.lighthouseci/*.html || echo "No .html files found"
          ls -al midaz-console/.lighthouseci/*.json || echo "No .json files found"

      # Upload de relatórios do Lighthouse CI
      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: |
            midaz-console/.lighthouseci/*.html
            midaz-console/.lighthouseci/*.json
          if-no-files-found: error

      # Limpeza do processo após o teste
      - name: Cleanup
        run: kill $(lsof -t -i:8081) || true
